kind: OrgStack
version: 1

org_stack:
  org_slug: acme
  base_domain: work-domain.xy

  platform:
    network: true
    postgres: true
    redis: true
    authentik: true
    proxy: false

  # apps:
  #   - name: forgejo
  #     enabled: true
  #     domain: git.work-domain.xy
  #     storage_size: 20Gi
  #   - name: custom_cms
  #     enabled: true
  #     domain: www.work-domain.xy
  #     version: v2.4.0
